
name: 'data_quality_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  data_quality_project:
    staging:
      +materialized: view
      +tags: ["staging"]
      +schema: staging
    marts:
      +materialized: table
      +tags: ["marts"]
      +schema: marts
    weekly_staging:
      +materialized: table
      +tags: ["weekly_staging"]
      +schema: weekly_staging
    weekly_custom:
      +materialized: view
      +tags: ["weekly_custom"]
      +schema: weekly_custom
    observability:
      +materialized: table
      +tags: ["observability"]
      +schema: observability

tests:
  +store_failures: true
  +schema: weekly_generic

flags:
  require_generic_test_arguments_property: true